### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by AlexPads** [MisteFr/AutoRestarter#1]
Hello :)

whenever I have this plugin installed no matter what I have the time set to the server sometimes just randomly restarts 

pump version: 3.2.3
MCPE: Win10
Php: 7.2
host: RAMShard :D

The server throws no errors or CrashDumps but jus randomly restarts for no reason at all o have the config set to 240Min (4Hrs) but it seem to restart every 30min to an Hr and I have tried to set the config Higher but It still randomly Restarts any idea as to why?

**Comment by MisteFr** [comment]
Hey @AlexPads,

Can you copy paste your config here and the version of the plugin you are using ?

Thanks !
